### ISSUE TITLE
SourceArray = cArray(SourceArray) ?

### ISSUE THREAD

**Issue by Cease** [todar/VBA-Arrays#3]
ArrayRemoveDuplicates() has this line:
"SourceArray = cArray(SourceArray)". "cArray" ?

Also, ArrayToRange assumes that this VBA code is used INSIDE Excel. Range should be replaced with Excel.Range.
Public Sub ArrayToRange(SourceArray As Variant, Optional ByRef Target As Excel.Range)

**Comment by todar** [comment]
Updated cArray() in ArrayRemoveDuplicates() with the proper function name, ConvertToArray(). I originally was sticking with Excels standard naming convention for casting, but later decided to make it more explicitly stated of what the function was doing. Thanks for creating an issue for this!

Also changed the target parameter data type to explicit Excel.Range. 

Please feel free to note any other errors or improvement! I, unfortunately, haven't had the time to do all the testing needed on all this code, and need to clean it up quite a bit of it.

Cheers!
